gem_perception_yolo:
  ros__parameters:
    image_topic: /oak/rgb/image_raw
    camera_info_topic: /oak/rgb/camera_info
    lidar_topic: /ouster/points
    prompt_topic: /perception/prompt
    camera_frame: front_single_camera_optical_link
    lidar_frame: ouster
    base_frame: base_link
    map_frame: map
    z_min_base: 0.15
    z_max_base: 5.0
    dbscan_eps: 0.4
    dbscan_min_samples: 3
    min_cluster_points: 3
    estimated_goal_distance: 15.0
    goal_hold_seconds: 2.0
    device: cuda

gem_perception_sam:
  ros__parameters:
    image_topic: /oak/rgb/image_raw
    camera_info_topic: /oak/rgb/camera_info
    lidar_topic: /ouster/points
    prompt_topic: /perception/prompt
    camera_frame: front_single_camera_optical_link
    lidar_frame: ouster
    base_frame: base_link
    map_frame: map
    z_min_base: 0.15
    z_max_base: 5.0
    dbscan_eps: 0.4
    dbscan_min_samples: 3
    min_cluster_points: 3
    estimated_goal_distance: 15.0
    goal_hold_seconds: 2.0
    device: cuda
    sam_type: sam2.1_hiera_small

map_tf_broadcaster:
  ros__parameters:
    ref_lat: 40.092722
    ref_lon: -88.236365

bev_overlay_node:
  ros__parameters:
    ref_lat: 40.092722
    ref_lon: -88.236365
